### ISSUE TITLE
Getting at Character Data

### ISSUE THREAD

**Issue by MidnightLightning** [EneaAntonicelli/unit-4-game#2]
https://github.com/EneaAntonicelli/unit-4-game/blob/36b362740e1c3c8a699b14b2f6e0514bbe180e86/assets/javascript/Non-Dynamic.js#L16-L22

The structure of the `characterArray` isn't a proper array declaration:

```js
var characterArray = [
        kenshiro = {
            name: "Kenshiro",
            technique: "Hokuto Shin Ken",
            hp: 120,
            attackPower: 8,
            image: '<img src="assets/images/kenshiro.png" class="image">'
        },
        mamiya = {
            name: "Mamiya",
            technique: "Yo-Yos, Emeici, Crossbow",
            hp: 120,
            attackPower: 8,
            image: '<img src="assets/images/mamiya.png" class="image">'
        },
// etc.
```
There shouldn't be equals signs in the middle of the declaration braces. Plus, the structure would probably best help you as an object itself, such that you can look up the characters by their ID:

```js
var characterDict = {
       kenshiro: {
            name: "Kenshiro",
            technique: "Hokuto Shin Ken",
            hp: 120,
            attackPower: 8,
            image: '<img src="assets/images/kenshiro.png" class="image">'
        },
        mamiya: {
            name: "Mamiya",
            technique: "Yo-Yos, Emeici, Crossbow",
            hp: 120,
            attackPower: 8,
            image: '<img src="assets/images/mamiya.png" class="image">'
        },
// etc.
```

Note that the overall item changed to an object (`{}` instead of `[]`), and the `=` assignments became `:`.

That way, when you get an HTML element with an ID, to get the associated character info, it's:

```js
$('.character').click(function () {
  if (heroChosen === false) {
    heroChosen = this;
    heroData = characterDict[this.id];
  }
});
```

**Comment by EneaAntonicelli** [comment]
So that last bit of code, that effectively gives me just the value in front of the Id correct? if I want to pull health technique, and attack power, do I need a new line for each one along with a .text?
```
$('.character').click(function () {
    if (heroChosen === false) {
    heroChosen = this;
    $('.hero.character.stats).append(characterDict[this.id);
    $('.hero.character.stats).append(characterDict[this.name);
    $('.hero.character.stats).append(characterDict[this.technique);
    $('.hero.character.stats).append(characterDict[this.health);
    }
});
```

**Comment by EneaAntonicelli** [comment]
hmm... seems to have unformatted for some reason...

**Comment by MidnightLightning** [comment]
Using triple-backticks around your code blocks (` ``` `) will keep them formatted like code ([GitHub formatting documentation](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)).

**Comment by MidnightLightning** [comment]
For getting at the data in that object, you're not quite there. Instead, you'd need:

```js
heroChosen = this; // heroChosen is now the HTML DOM object
heroData = characterDict[this.id]; // heroData is one whole object with its own properties.
var $container = $('.hero.character.stats'); // Since you're using it multiple times, have jQuery just fetch it once, and save a reference to it.

$container.append("ID: " + this.id);
$container.append("Name: " + heroData.name);
$container.append("Technique: " + heroData.technique);
$container.append("Health: " + heroData.hp);
```

**Comment by EneaAntonicelli** [comment]
man... see this is the demoralizing bit.. I would never think to do it this way... It makes perfect sense and looks so incredibly elegant in comparison to all the code I have been trying to cram in my head over the past week... I wish I could undo all the obstructions in my head now and adopt this...

**Comment by MidnightLightning** [comment]
Don't worry about it! You're doing well with the basic concepts, and the first step is always "get it to work". The code you pasted in above, if I fix up the closing quotes and square brackets is:

```js
heroChosen = this;
$('.hero.character.stats').append(characterDict[this.id].name);
$('.hero.character.stats').append(characterDict[this.id].technique);
$('.hero.character.stats').append(characterDict[this.id].hp);
```

That code would definitely work, and for a simple exercise like this would be fine. Then the next step as a developer is to notice the fact that a lot of those lines are repeated (really, the only thing that changed in those last three lines the `name`, `technique` and `hp` text). One good principle of programming is "Don't Repeat Yourself (DRY principle), and so that area of code should then jump out at you as a prime candidate to see if you couldn't refactor it to not repeat so much of the code. It helps in the long-run as your code for the project grows, and the more code you write the more those opportunities will be more evident to you.

**Comment by EneaAntonicelli** [comment]
I see what your saying. So I suppose the only thing i am slightly confused about at this point, is the concept of "id". Because you initiated it by stating 
```heroData = characterDict[this.id];```
And then after that, it somehow held ALL properties of that object. When you are now calling [this.id] which is basically stating "this" as in "the object or character that was clicked", its ID, well to me that is one name/value of the object.. i am not sure how it can pull all other name/values with it or how it is being used as an anchor pointer.

How can I visualize this?

**Comment by EneaAntonicelli** [comment]
is that interchangeable with [this.name] or [this.technique] ? how does "ID" become so important?

**Comment by EneaAntonicelli** [comment]
is it some inherent value or term that javascript provides and I just need to learn it at face value?

**Comment by MidnightLightning** [comment]
> the only thing i am slightly confused about at this point, is the concept of "id".

> is it some inherent value or term that javascript provides and I just need to learn it at face value?

In your HTML, you created an element with an `id` attribute:

```html
<div class="character col-md-2 col-sm-4 col-xs-6 .enemy" id="mamiya">
```

The way that Javascript interacts with HTML elements indicates that if you set an `id` on the HTML element, it will be accessible via the `id` attribute of [the Javascript that represents that HTML element](https://developer.mozilla.org/en-US/docs/Web/API/Element/id) when appropriate.

For the click handler, the way browsers handle it is to set the `this` variable (a special variable in Javascript that changes with whatever "context" a function is called in) is to set it to the HTML element that was clicked.

That much is something you do need to just learn and memorize (or at least know where to go to find a reference to remember what a certain attribute is called). For javascript running in the browser, `console.log(this)` can help you figure out  what options are on whatever `this` happens to be at a given time (and learning to use a browser debugger can help with just seeing what variables are available at a given moment in your script's execution).

> Because you initiated it by stating
> ```js
> heroData = characterDict[this.id];
> ```
>And then after that, it somehow held ALL properties of that object. 

Yes; that "somehow" is a concept fundamental to programming (not just Javascript). In that case, we made a copy of the item out of the array and just used the copy instead.  Try this in your browser's Javascript console to illustrate that

```js
var a = ['Foo', 'Bar', 'Baz']; // Save an array of strings
var b = a[1]; // Copy the value from the item at index 1 and save it as "b"
console.log(b); // "Bar"
a[1] = "Nutty"; // Update one element of the array
console.log(a): // "['Foo', 'Nutty', 'Baz']" We updated one element, but the others were untouched
console.log(b); // "Bar"  This one wasn't updated either, since it was a copy
```
Because you know your `characterDict` chunk of data isn't going to change, creating a copy of part of it is fine, and it makes it easier for you to reference the copy. Make sense?

**Comment by MidnightLightning** [comment]
Oh, and part of what might be confusing you is the syntax for a dynamic property; for example:

```js
var testObject = {
  id: 'special',
  name: 'My Special Object',
  age: 'very new',
  appearance: 'shiny',
  "hyper-active": true   // <-- Because this one has a dash in its name, we need to put quotes around it when defining it (otherwise it would be interpreted as a minus sign and Javascript would try and do math with it)
};
console.log(testObject.name): // "My Special Object" <-- When it's a simple property, we can use "dot notation"
console.log(testObject['name']); // "My Special Object" <-- Alternate syntax for exactly the same thing
console.log(testObject.hyper-active); // NaN <-- Doesn't work; Javascript thinks you're trying to subtract two things, so looks for a "testObject.hyper" property (which doesn't exist), and tries to find a variable called "active" (doesn't exist) and subtracts them.
console.log(testObject['hyper-active']); // "true" <-- Need to use the square-bracket syntax for names with dashes.

var foo = 'appearance'; // Save the string "appearance" into the variable "foo"
console.log(testObject.foo); // "undefined" <-- The testObject has no property called "foo"
console.log(testObject['foo']; // "undefined" <-- Nope, still doesn't have a property called "foo"
console.log(testObject[foo]); // "shiny" <-- Note there's no quotation marks here. We're not using the string "foo" into the square brackets, but the variable called foo. The value of foo at that moment was "appearance", so the value of testObject.appearance is logged
```

So, the syntax of `characterDict[this.id]` means "Look up the `id` property on the `this` object. Take that string (i.e. "mamiya") and look up a property in the `characterDict` object with that name. We cannot use dot-syntax when looking up in the `characterDict` here, because when writing the code, we don't know what the string is we want to look up. We could write it as using square brackets for both expressions (`characterDict[this['id']]`; that does the same thing), but most Javascript developers use dot-syntax wherever possible (since it's less characters to type), and only use square-bracket syntax when dot-syntax doesn't work.

**Comment by EneaAntonicelli** [comment]
Ok, I think i understand that. Thank you for the thorough explanation. Could you take a look at the most current code? I added some things I thought would work but the data is still not carrying over. Where is my fault?

**Comment by EneaAntonicelli** [comment]
I am basically populating the data but it is running through three times.. giving me three chunks

**Comment by EneaAntonicelli** [comment]
It's the .stats which is attributed to each h3 that is being referenced 3 times... not sure how to make them independent.
